### ISSUE TITLE
How to generate token by using RS512 Algorithym?

### ISSUE THREAD

**Issue by Mirmuxsin** [stechstudio/laravel-jwt#10]
As I understand, I have to put my private key in `signWith('custom-signing-key-with-256-bits')` method to generate with custom algorithm. But it says 256bits and I want to generate it for 512 bits. I tried to put there my private key which generated by using RS512 algorithm, but it doesnt generate valid JWT token for that

**Comment by jszobody** [comment]
I have `Sha256` set up as the default signer. 

https://github.com/stechstudio/laravel-jwt/blob/afdb8205c0fc744be8593009d3598ea390a1cee9/config/jwt.php#L8

You can publish the config file and change it to whatever signer you want to use. 

https://lcobucci-jwt.readthedocs.io/en/latest/supported-algorithms/

There's the list of signers available. So long as you configure a signer that works with the key you provide, you should be all set.
