### ISSUE TITLE
Add an auth middleware

### ISSUE THREAD

**Issue by shadoWalker89** [stechstudio/laravel-jwt#7]
Hi,

This package looks nice.
I hope that you can add an auth middleware that can identify the authenticated user to reduce any code needed in apps using this package.

**Comment by jszobody** [comment]
Hi @shadoWalker89. There is a lot more to handling authentication than just middleware. Other mature, popular packages already handle JWT authentication, like this one:

https://github.com/tymondesigns/jwt-auth

I'm not sure I want to overlap and provide the same functionality. Perhaps you can explain further if this `jwt-auth` package above isn't a fit for your needs?
