### ISSUE TITLE
Maybe README.md update is needed.

### ISSUE THREAD

**Issue by reekol** [stechstudio/laravel-jwt#9]
Looks like there is no JWT::setId method.  
Following the documentation 
```php
        $jwt = \JWT::setId($myId);
``` 
leads to ..
```php
Call to undefined method STS\\JWT\\Client::setId()
```

Looking through the code of the library i found out that default method used is.
```php
  ->identifiedBy($id)
```  

![Screenshot_20240629_182728](https://github.com/stechstudio/laravel-jwt/assets/19834806/ea364482-58ca-42dd-9024-63829fe87aa8)

README.md not up to date?

Cheers. And thank you for this library!

**Comment by jszobody** [comment]
Fixed. Thanks!
